# Claude API
anthropic.api.key=TU_API_KEY_AQUI
anthropic.api.url=https://api.anthropic.com/v1/messages
anthropic.model=claude-sonnet-4-6

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/tutordb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Email Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alexis.martiarenar@gmail.com
spring.mail.password=zgcwzqpwltvhcrud
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App
server.port=9999
app.nombre.estudiante=Alexis Leonardo
app.fecha.inicio.prepa=2026-08-15
app.email.papa=alexis.martiarenar@gmail.com
app.email.mama=adrianavazquezr@gmail.com
app.dias.entre.examenes=3
app.horas.estudio=2

# Logging a archivo
logging.file.name=logs/tutor-alexis.log
logging.level.com.tutor.alexis=DEBUG
logging.level.org.springframework=WARN
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n